name: Drupal PHPCS

on:
  pull_request:
    paths:
      - "{docroot,web}/{modules,themes}/custom/**/*.{php,module,inc,install,profile,theme,yml}"

env:
  PHP_VERSION: 8.1

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Determine PHP version
        run: |
          if [ -f .platform.app.yaml ]; then
            echo "PHP_VERSION=$(grep -oP "type: 'php:\K[0-9]\.[0-9]'" .platform.app.yaml)" >> $GITHUB_ENV
          fi

      - name: Setup PHP ${{ env.PHP_VERSION }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          tools: "cs2pr, phpcs, composer"

      - name: Install Drupal Coder
        run: |
          composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer global require --ignore-platform-reqs drupal/coder

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: "{docroot,web}/{modules,themes}/custom/**/*.{php,module,inc,install,profile,theme,yml}"
          files_ignore: |
            *Test.php
            *TestBase.php
            **/tests/

      - name: PHPCS
        run: |
          if [ -z "${{ steps.changed-files.outputs.all_changed_files }}" ]; then
            echo "No relevant files changed."
            exit 0
          fi

          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            phpcs -q --report=checkstyle --standard=Drupal,DrupalPractice -n "$file" | cs2pr
          done
